# Generated by Django 4.0.4 on 2022-06-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"ordering": ["-created_date"]},
        ),
    ]
